'use client'

import { useCallback, useState } from 'react'
import type { StudentWalletSummary } from '@/features/wallets/domain'
import { WalletSearch } from '@/features/wallets/ui/WalletSearch'
import { requestStepUp,postPinReset,postCardReset } from '@/features/security/client'
import { CardReaderCapture } from '@/features/terminal/CardReaderCapture'

export function SecurityScreen(){const[student,setStudent]=useState<StudentWalletSummary|null>(null);const[purpose,setPurpose]=useState<'RESET_STUDENT_PIN'|'RESET_STUDENT_CARD'>('RESET_STUDENT_PIN');const[adminCode,setAdminCode]=useState('');const[adminPin,setAdminPin]=useState('');const[token,setToken]=useState<string|null>(null);const[newPin,setNewPin]=useState('');const[confirmPin,setConfirmPin]=useState('');const[reader,setReader]=useState(false);const[message,setMessage]=useState<string|null>(null)
 async function authorize(){if(!student)return;try{const r=await requestStepUp({superAdminEmployeeCode:adminCode,superAdminPin:adminPin,purpose,studentId:student.student_id});setAdminPin('');setToken(r.authorizationToken);setMessage('One-use authorization issued for 60 seconds.')}catch(e){setAdminPin('');setMessage(e instanceof Error?e.message:'Authorization failed')}}
 async function resetPin(e:React.FormEvent){e.preventDefault();if(!student||!token)return;try{await postPinReset(student.student_id,{authorizationToken:token,newPin,confirmationPin:confirmPin});setNewPin('');setConfirmPin('');setToken(null);setMessage('Student PIN reset. No PIN value was logged or returned.')}catch(err){setMessage(err instanceof Error?err.message:'Reset failed')}}
 const readCard=useCallback(async(value:string)=>{if(!student||!token)return;setReader(false);try{await postCardReset(student.student_id,{authorizationToken:token,newCardRead:value});setToken(null);setMessage('Old card deactivated and replacement card registered.')}catch(err){setMessage(err instanceof Error?err.message:'Card reset failed')}},[student,token])
 return <main className="workspace"><CardReaderCapture active={reader} onRead={readCard}/><header className="workspace-header"><div><p className="eyebrow">Protected credentials</p><h1>PIN and card replacement</h1></div><span className="status-pill">Super-admin step-up</span></header><div className="dashboard-grid"><WalletSearch onSelect={setStudent}/><section className="panel"><div className="panel-heading"><div><p className="eyebrow">One student · one purpose · one use</p><h2>Reset authorization</h2></div></div>{student?<><div className="student-summary"><strong>{student.display_name}</strong><span>{student.student_code}</span></div><div className="segmented"><button className={purpose==='RESET_STUDENT_PIN'?'active':''} onClick={()=>{setPurpose('RESET_STUDENT_PIN');setToken(null)}}>Reset PIN</button><button className={purpose==='RESET_STUDENT_CARD'?'active':''} onClick={()=>{setPurpose('RESET_STUDENT_CARD');setToken(null)}}>Replace card</button></div><label className="field"><span>Super-admin employee ID</span><input value={adminCode} onChange={e=>setAdminCode(e.target.value)}/></label><label className="field"><span>Super-admin PIN</span><input type="password" inputMode="numeric" autoComplete="off" value={adminPin} onChange={e=>setAdminPin(e.target.value.replace(/\D/g,'').slice(0,16))}/></label><button className="secondary-action" disabled={!adminCode||adminPin.length<4} onClick={()=>void authorize()}>Authorize protected action</button>{token&&purpose==='RESET_STUDENT_PIN'&&<form onSubmit={resetPin}><label className="field"><span>Student enters new PIN</span><input type="password" inputMode="numeric" value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,'').slice(0,12))}/></label><label className="field"><span>Student confirms new PIN</span><input type="password" inputMode="numeric" value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,'').slice(0,12))}/></label><button className="primary-action" disabled={newPin.length<4||newPin!==confirmPin}>Complete PIN reset</button></form>}{token&&purpose==='RESET_STUDENT_CARD'&&<button className="primary-action" onClick={()=>setReader(true)}>Arm reader for replacement card</button>}{reader&&<div className="reader-state"><span className="reader-dot"/>Scan one replacement card</div>}</>:<p className="muted">Select a student from the read-only list.</p>}{message&&<p className="form-message">{message}</p>}</section></div></main>}
