import {describe,it,expect} from 'vitest'
import {CAPABILITIES,PRESETS,PRESET_DEFAULTS,validCapabilities,setCapability,accessDiff,effectiveAccess,type Capability} from '@/features/auth/capabilities'
import {WORKSPACE_LINKS,canAccessWorkspace,visibleSections,defaultEffectiveWorkspace} from '@/features/auth/navigation'
import {AccessChangeSchema,AccessPermissionsSchema,AccessRecoverySchema} from '../domain'
const spaces=(p:readonly Capability[])=>WORKSPACE_LINKS.filter(l=>canAccessWorkspace(p,l)).map(l=>l.label)
describe('explicit effective capabilities',()=>{
 it.each(PRESETS)('%s defaults have complete prerequisites and no duplicates',p=>expect(validCapabilities(PRESET_DEFAULTS[p])).toBe(true))
 it('conservative Staff defaults only permit routine checkout',()=>{expect(PRESET_DEFAULTS.staff).toEqual(['pos.read','pos.checkout','coupons.redeem']);expect(spaces(PRESET_DEFAULTS.staff)).toEqual(['Register']);expect(visibleSections(PRESET_DEFAULTS.staff,'Register').map(s=>s.label)).toEqual(['POS']);expect(defaultEffectiveWorkspace(PRESET_DEFAULTS.staff)).toBe('/pos')})
 it('Manager operations do not grant administrator or exceptional wallet authority',()=>{expect(spaces(PRESET_DEFAULTS.manager)).toEqual(['Register','Students','Inventory','Finance']);for(const c of ['staff.access.manage','staff.manage','wallet.correct','wallet.reverse','settings.payments.manage'])expect(PRESET_DEFAULTS.manager).not.toContain(c)})
 it('Accountant financial access has no unrelated operational management',()=>{expect(spaces(PRESET_DEFAULTS.accountant)).toEqual(['Register','Students','Finance']);for(const c of ['inventory.price.manage','staff.manage','credentials.reset','students.enroll','students.status.manage','terminals.manage'])expect(PRESET_DEFAULTS.accountant).not.toContain(c)})
 it('Super Admin receives defined capabilities and still has separate approval cells',()=>{expect(new Set(PRESET_DEFAULTS.super_admin)).toEqual(new Set(CAPABILITIES.map(c=>c.name)));expect(CAPABILITIES.filter(c=>c.column==='Approve').map(c=>c.name)).toContain('wallet.approve')})
 it('Staff + Orders sees Orders without another workspace or unrelated actions',()=>{const p=setCapability([...PRESET_DEFAULTS.staff],'orders.fulfill',true).permissions;expect(p).toContain('orders.read');expect(spaces(p)).toEqual(['Register']);expect(visibleSections(p,'Register').map(s=>s.label)).toEqual(['POS','Orders']);expect(p).not.toContain('cash.shift.manage')})
 it('Manager + Students Status minus Credentials is independent of credential/reset authority',()=>{const p=setCapability([...PRESET_DEFAULTS.manager],'students.status.manage',true).permissions;expect(p).toContain('students.read');expect(p).not.toContain('credentials.reset');expect(p).not.toContain('staff.access.manage')})
 it('Wallet Operate adds only its transitive prerequisites and explains them',()=>{const result=setCapability([],'wallet.fund',true);expect(new Set(result.permissions)).toEqual(new Set(['students.read','wallet.read','wallet.fund']));expect(result.prerequisites).toContain('wallet.read');expect(spaces(result.permissions)).toEqual(['Students']);expect(result.permissions).not.toContain('wallet.correct')})
 it('removing a prerequisite also removes dependent permissions recursively',()=>{const p=setCapability([],'wallet.fund',true).permissions;expect(setCapability(p,'wallet.read',false).permissions).toEqual(['students.read']);const products=setCapability([],'inventory.product.manage',true).permissions;expect(setCapability(products,'inventory.read',false).permissions).toEqual([])})
 it.each(CAPABILITIES.filter(c=>c.requires?.length))('$name cannot be saved without prerequisites',c=>{expect(AccessPermissionsSchema.safeParse([c.name]).success).toBe(false);expect(validCapabilities(setCapability([],c.name,true).permissions)).toBe(true)})
 it('empty effective access yields no workspace regardless of any preset label',()=>{expect(spaces([])).toEqual([]);expect(defaultEffectiveWorkspace([])).toBe('/access-unavailable');expect(effectiveAccess([]).every(w=>w.actions.length===0)).toBe(true)})
 it('diff and summary are generated from stored permission sets',()=>{expect(accessDiff(['pos.read'],['students.read'])).toEqual({added:['students.read'],removed:['pos.read']});const summary=effectiveAccess(['students.read','wallet.read','wallet.fund']);expect(summary.find(w=>w.workspace==='Students')?.actions.map(c=>c.name)).toContain('wallet.fund');expect(summary.find(w=>w.workspace==='Admin')?.actions).toEqual([])})
})
describe('access change contracts',()=>{
 const v={requestKey:'10000000-0000-4000-8000-000000000001',targetId:'10000000-0000-4000-8000-000000000002',expectedRevision:1,previousPreset:'staff',previousPermissions:['pos.read'],newPreset:'staff',permissions:['pos.read','pos.checkout'],adminPin:'00123456',reason:'Employee assignment reviewed',confirmed:true}
 it('requires target, previous and proposed snapshots, reason and current PIN',()=>expect(AccessChangeSchema.parse(v)).toEqual(v))
 it.each([{confirmed:false},{expectedRevision:0},{adminPin:'123'},{reason:'short'},{reason:'Controls\nare not accepted'},{permissions:['wallet.fund']},{permissions:['pos.read','pos.read']},{permissions:['unknown']},{role:'super_admin'},{targetId:'bad'}])('rejects an invalid access assignment %#',extra=>expect(AccessChangeSchema.safeParse({...v,...extra}).success).toBe(false))
 it('recovery stores only an opaque request ID',()=>{expect(AccessRecoverySchema.parse({requestKey:v.requestKey})).toEqual({requestKey:v.requestKey});expect(AccessRecoverySchema.safeParse({requestKey:v.requestKey,adminPin:v.adminPin}).success).toBe(false)})
})
